# Generated by Django 5.2.3 on 2025-07-07 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_address_remove_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number must be 11 digits', regex='^\\d{11}')]),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
