# Generated by Django 5.2.1 on 2025-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_mobile_number_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
